import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";

const Services = () => (
  <>
    <Helmet><title>Services – Welding, Furniture, Construction | SAMPE Liberia</title></Helmet>
    <div className="container mx-auto px-4 py-16">
      <div className="text-center mb-16"><h1 className="text-5xl font-bold mb-4">Expert Solutions for Every Project</h1><p className="text-xl text-gray-600">From structural steel to bespoke cabinetry, we combine technical precision with artistic flair.</p><div className="flex justify-center gap-4 mt-6"><Link to="/quote" className="bg-primary px-6 py-2 rounded-full text-white">REQUEST A QUOTE</Link><Link to="/gallery" className="border border-primary text-primary px-6 py-2 rounded-full">VIEW PORTFOLIO</Link></div></div>
      <div className="grid md:grid-cols-3 gap-12 mb-20"><div className="bg-gray-50 p-6 rounded-2xl"><h2 className="text-2xl font-bold text-primary mb-3">Welding & Fabrication</h2><p className="mb-3">Precision metalwork designed for durability and aesthetic impact.</p><ul className="list-disc list-inside space-y-1"><li>Custom Iron Doors & Gates</li><li>Security Window Bars & Fencing</li><li>Bespoke Architectural Metalwork</li></ul><Link to="/quote" className="inline-block mt-4 text-primary font-semibold">REQUEST A QUOTE →</Link></div><div className="bg-gray-50 p-6 rounded-2xl"><h2 className="text-2xl font-bold text-primary mb-3">Bespoke Furniture</h2><p>Custom bed frames, office suites, and sustainable materials.</p><div className="mt-3 space-y-2"><p><strong>CUSTOM BED FRAMES</strong><br/>Handcrafted solid wood and steel frames.</p><p><strong>OFFICE SUITES</strong><br/>Professional offices and desks for your business.</p></div></div><div className="bg-gray-50 p-6 rounded-2xl"><h2 className="text-2xl font-bold text-primary mb-3">General Construction & Renovations</h2><ul className="list-disc list-inside"><li>New Projects – ground‑up construction</li><li>Renovations – structural modifications</li><li>Structural Installations – beams, support systems</li></ul><Link to="/quote" className="inline-block mt-4 text-primary font-semibold">GET QUOTE →</Link></div></div>
      <div className="bg-darker text-white rounded-2xl p-8 mb-16"><h2 className="text-2xl font-bold text-center mb-8">OUR METHODOLOGY: PRECISE EXECUTION FROM CONCEPT TO COMPLETION</h2><div className="grid md:grid-cols-4 gap-6 text-center"><div><div className="text-3xl font-bold text-primary">1.</div><h3 className="font-bold">CONSULTATION</h3><p className="text-sm">Site analysis and requirements gathering</p></div><div><div className="text-3xl font-bold text-primary">2.</div><h3 className="font-bold">DESIGN</h3><p className="text-sm">CAD drafting and 3D modeling</p></div><div><div className="text-3xl font-bold text-primary">3.</div><h3 className="font-bold">FABRICATION</h3><p className="text-sm">Precision crafting in our shop</p></div><div><div className="text-3xl font-bold text-primary">4.</div><h3 className="font-bold">INSTALLATION</h3><p className="text-sm">Seamless on‑site assembly</p></div></div></div>
      <div className="text-center"><Link to="/quote" className="bg-primary text-white px-8 py-3 rounded-full font-bold text-lg">REQUEST A FULL QUOTE</Link></div>
    </div>
  </>
);
export default Services;
